pipeline {
    agent any

    stages {

        stage('Docker Build') {
            steps {
                dir('front') {
                    sh "docker build -t seesaw_front:latest ."
                }
            }

            post {
                success {
                    echo 'docker build success'
                }

                failure {
                    echo 'docker build failed'
                }
            }
        }


        stage('deploy') {// 배포 스테이지: 이전에 실행 중인 'seesawbank_back' 컨테이너를 제거하고 새로운 이미지로 컨테이너를 실행
            steps {
                // 실행중인 컨테이너 제거
                sh 'docker rm -f seesaw_front'
                // 새로운 이미지 실행
                sh 'docker run -d --name seesaw_front -p 3000:3000 -e TZ=Asia/Seoul -u root seesaw_front:latest'
            }

            post {
                success {
                    echo 'deploy success'
                }

                failure {
                    echo 'deploy failed'
                }
            }
        }

    }
}

