export const categoryList = [
  '전체',
  '식비',
  '카페/간식',
  '술/유흥',
  '생활',
  '온라인쇼핑',
  '패션/쇼핑',
  '뷰티/미용',
  '교통',
  '자동차',
  '주거/통신',
  '의료/건강',
  '금융',
  '문화/여가',
  '여행/숙박',
  '교육/학습',
  '자녀/육아',
  '반려동물',
  '경조/선물',
  '편의점',
  '미분류',
]

export const capsuleColor: Record<string, Record<string, string>> = {
  bg: {
    '0': 'bg-category-0',
    '1': 'bg-category-1',
    '2': 'bg-category-3',
    '3': 'bg-category-2',
    '4': 'bg-category-4',
    '5': 'bg-category-5',
    '6': 'bg-category-6',
    '7': 'bg-category-7',
    '8': 'bg-category-8',
    '9': 'bg-category-9',
    '10': 'bg-category-10',
    '11': 'bg-category-11',
    '12': 'bg-category-12',
    '13': 'bg-category-13',
    '14': 'bg-category-14',
    '15': 'bg-category-15',
    '16': 'bg-category-16',
    '17': 'bg-category-17',
    '18': 'bg-category-18',
    '19': 'bg-category-19',
    '20': 'bg-category-20',
    'background-fill': 'bg-background-fill',
    background: 'bg-background',
    primary: 'bg-primary',
    'primary-container': 'bg-primary-container',
    black: 'bg-black',
  },
  text: {
    '0': 'text-category-0',
    '1': 'text-category-1',
    '2': 'text-category-3',
    '3': 'text-category-2',
    '4': 'text-category-4',
    '5': 'text-category-5',
    '6': 'text-category-6',
    '7': 'text-category-7',
    '8': 'text-category-8',
    '9': 'text-category-9',
    '10': 'text-category-10',
    '11': 'text-category-11',
    '12': 'text-category-12',
    '13': 'text-category-13',
    '14': 'text-category-14',
    '15': 'text-category-15',
    '16': 'text-category-16',
    '17': 'text-category-17',
    '18': 'text-category-18',
    '19': 'text-category-19',
    '20': 'text-category-20',
    black: 'text-black',
    primary: 'text-primary',
    background: 'text-background',
  },
}

export const categoryColors = {
  'category-0': '#001B2A',
  'category-1': '#E98080',
  'category-3': '#FEB087',
  'category-2': '#FFAD69',
  'category-4': '#FFC875',
  'category-5': '#FFE681',
  'category-6': '#FFF16A',
  'category-7': '#DAE475',
  'category-8': '#BEDEAD',
  'category-9': '#85D7B5',
  'category-10': '#65E0D0',
  'category-11': '#74EFF5',
  'category-12': '#83DFF4',
  'category-13': '#8ED7E6',
  'category-14': '#75BAE2',
  'category-15': '#A6C4F1',
  'category-16': '#8AA1E2',
  'category-17': '#AB8AE2',
  'category-18': '#F287C7',
  'category-19': '#FEBAAD',
  'category-20': '#DE68C4',
}

export const iconColors: Record<number, string> = {
  0: '#001B2A',
  1: '#E98080',
  3: '#FEB087',
  2: '#FFAD69',
  4: '#FFC875',
  5: '#FFE681',
  6: '#FFF16A',
  7: '#DAE475',
  8: '#BEDEAD',
  9: '#85D7B5',
  10: '#65E0D0',
  11: '#74EFF5',
  12: '#83DFF4',
  13: '#8ED7E6',
  14: '#75BAE2',
  15: '#A6C4F1',
  16: '#8AA1E2',
  17: '#AB8AE2',
  18: '#F287C7',
  19: '#FEBAAD',
  20: '#DE68C4',
}

export const missionPeriodArray = [
  ,
  '매일',
  '2일당 한 번',
  '3일당 한 번',
  '4일당 한 번',
  '5일당 한 번',
  '6일당 한 번',
  '7일당 한 번',
]

export const missionCycleArray = [
  ,
  '1주',
  '2주',
  '3주',
  '4주',
  ,
  '6주',
  ,
  '8주',
  ,
  ,
  ,
  '12주',
]

// 죽는줄
import { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faUtensils,
  faMugHot,
  faChampagneGlasses,
  faHouse,
  faCartShopping,
  faShirt,
  faGem,
  faBus,
  faCar,
  faMobileScreenButton,
  faBriefcaseMedical,
  faWonSign,
  faTicket,
  faPlane,
  faBookOpen,
  faBaby,
  faPaw,
  faGift,
  faStore,
  faCircleQuestion,
} from '@fortawesome/free-solid-svg-icons'
export const categoryIcon: Record<number, IconDefinition> = {
  1: faUtensils,
  2: faMugHot,
  3: faChampagneGlasses,
  4: faHouse,
  5: faCartShopping,
  6: faShirt,
  7: faGem,
  8: faBus,
  9: faCar,
  10: faMobileScreenButton,
  11: faBriefcaseMedical,
  12: faWonSign,
  13: faTicket,
  14: faPlane,
  15: faBookOpen,
  16: faBaby,
  17: faPaw,
  18: faGift,
  19: faStore,
  20: faCircleQuestion,
}
